# Generated by Django 4.1.7 on 2023-04-23 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('city_name', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('sector', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Energy', 'Energy'), ('Logistics', 'Logistics'), ('Construction', 'Construction'), ('Education', 'Education'), ('Health', 'Health'), ('Manufacturing', 'Manufacturing'), ('Cleaning', 'Cleaning'), ('Education', 'Education'), ('Finance', 'Finance'), ('Tourism', 'Tourism'), ('IT', 'iT'), ('Agriculture', 'Agriculture'), ('Others', 'Others')], max_length=50)),
                ('other_sector', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/startup')),
            ],
        ),
        migrations.CreateModel(
            name='EthRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Dire Dawa', 'Dire Dawa'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Sidama', 'Sidama '), ('South West Peoples', 'South West'), ('SNNP', 'SNNP'), ('Tigray', 'Tigray')], max_length=50)),
            ],
            options={
                'verbose_name': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middile_name', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('profile_pic', models.ImageField(upload_to='user_pic/%Y/%m/%d', validators=[main.models.validate_image])),
                ('contact', models.CharField(max_length=15)),
                ('secondary_email', models.EmailField(max_length=150)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(blank=True, to='main.profile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wereda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wereda_name', models.CharField(max_length=30)),
                ('regionId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wereda', to='main.ethregion', verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_year', models.DateField()),
                ('market_scope', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=50)),
                ('stage', models.CharField(choices=[('pre start-up( early-stage)', 'pre start-up( early-stage)'), ('mid start-up', 'mid start-up'), ('in-market', 'in-market')], max_length=50)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='startup_address', to='main.address')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='startup_description', to='main.description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationalLevel', models.CharField(max_length=50)),
                ('educational_background', models.CharField(max_length=50)),
                ('mentor_area', models.CharField(max_length=50)),
                ('airelated_expriance', models.CharField(max_length=50)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='mentor/attachments')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mentor_address', to='main.address')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mentor_description', to='main.description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='IncubatorsAccelatorsHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Acceleration', 'Acceleration'), ('Incubation', 'Incubation'), ('Hub', 'Hub')], max_length=50)),
                ('ownership', models.CharField(choices=[('Private', 'Private'), ('Public', 'Incubation'), ('NGO', 'nGO'), ('Government', 'Government'), ('Other', 'Other')], max_length=50)),
                ('focusIndustry', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('pre', 'Pre-Startup'), ('mid', 'Mid-Startup'), ('early', 'Early Trsction'), ('market', 'In-Market')], max_length=50)),
                ('funded_by', models.CharField(choices=[('self_', 'self'), ('government', 'government'), ('nGO', 'NGO'), ('grant', 'Grant'), ('International', 'International'), ('Other', 'Other')], max_length=50)),
                ('funded_by_other', models.CharField(max_length=50)),
                ('program_duration', models.CharField(choices=[('less_than_3_month', 'less than 3 month'), ('3_to_6 months', '3 to 6 months'), ('6_months_to_a_year', '6 months to a year'), ('1_year_to_two_years', '1 year to two years'), ('International', 'International'), ('Other', 'Other')], max_length=50)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='incubetor/attachments')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iha_address', to='main.address')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iha_description', to='main.description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iha_address', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Goveroment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goveroment_type', models.CharField(choices=[('ministry_offices', 'Ministry offices'), ('universities', 'Universities'), ('other', 'other')], max_length=50)),
                ('goveroment_type_other', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('pre', 'Pre-Startup'), ('mid', 'Mid-Startup'), ('early', 'Early Trsction'), ('market', 'In-Market')], max_length=50)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goveroment_address', to='main.address')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goveroment_description', to='main.description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DonorFunder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner_type', models.CharField(choices=[('self_', 'self'), ('government', 'government'), ('nGO', 'NGO'), ('grant', 'Grant'), ('International', 'International'), ('Other', 'Other')], max_length=50)),
                ('funded_by_other', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('pre', 'Pre-Startup'), ('mid', 'Mid-Startup'), ('early', 'Early Trsction'), ('market', 'In-Market')], max_length=50)),
                ('investment_type', models.CharField(choices=[('selection', 'selection'), ('finance', 'finance'), ('working_space', 'working space'), ('material', 'material'), ('other', 'other')], max_length=50)),
                ('investment_type_other', models.CharField(max_length=50)),
                ('maxInvestRange', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='donor_address', to='main.address')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='donor_description', to='main.description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='donor_profile', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='main.wereda'),
        ),
    ]
