# Generated by Django 4.1.7 on 2023-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('svg', models.FileField(blank=True, help_text='please upload relevant documents max 10', null=True, upload_to='description/svg', verbose_name='svg')),
            ],
        ),
    ]
