# Generated by Django 4.1.7 on 2023-05-04 18:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='focusIndustry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Energy', 'Energy'), ('Logistics', 'Logistics'), ('Construction', 'Construction'), ('Education', 'Education'), ('Health', 'Health'), ('Manufacturing', 'Manufacturing'), ('Cleaning', 'Cleaning'), ('Education', 'Education'), ('Finance', 'Finance'), ('Tourism', 'Tourism'), ('IT', 'IT'), ('Agriculture', 'Agriculture'), ('Other', 'Other')], max_length=500), default=list, size=None),
        ),
    ]
