# Generated by Django 4.1.7 on 2023-05-04 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_incubatorsaccelatorshub_focusindustry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='focusIndustry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
    ]
