# Generated by Django 4.1.7 on 2023-05-15 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='to_user',
        ),
        migrations.AddField(
            model_name='connect',
            name='connect_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='connect_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='connect_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='connect_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='message_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='message_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
