# Generated by Django 4.1.7 on 2023-05-05 07:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_donorfunder_investment_type_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorfunder',
            name='doner_type_by_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donorfunder',
            name='investment_type',
            field=models.CharField(choices=[('selection', 'selection'), ('finance', 'finance'), ('working_space', 'working space'), ('material', 'material'), ('Other', 'Other')], max_length=50, verbose_name='Investment Type'),
        ),
        migrations.AlterField(
            model_name='goveroment',
            name='level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=20),
        ),
    ]
