# Generated by Django 4.1.7 on 2023-05-15 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_messages_message_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message_to',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='message_from',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='connect_from',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='connect_to',
        ),
        migrations.AddField(
            model_name='connect',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
