# Generated by Django 4.1.7 on 2023-05-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_connect_is_accepted_connect_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethregion',
            name='region_name',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Dire Dawa', 'Dire Dawa'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Sidama', 'Sidama '), ('South West Peoples', 'South West'), ('SNNP', 'SNNP'), ('Tigray', 'Tigray')], max_length=50, unique=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='airelated_expriance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AI Related Experience'),
        ),
        migrations.AlterField(
            model_name='wereda',
            name='wereda_name',
            field=models.CharField(max_length=30, verbose_name='Wereda'),
        ),
    ]
