# Generated by Django 4.1.7 on 2023-04-28 08:06

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_startup_establishment_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethregion',
            options={},
        ),
        migrations.RenameField(
            model_name='donorfunder',
            old_name='funded_by_other',
            new_name='doner_type_by_other',
        ),
        migrations.AlterField(
            model_name='address',
            name='city_name',
            field=models.CharField(max_length=30, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='main.wereda', verbose_name='Wereda'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='website',
            field=models.CharField(max_length=30, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='description',
            name='sector',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Energy', 'Energy'), ('Logistics', 'Logistics'), ('Construction', 'Construction'), ('Education', 'Education'), ('Health', 'Health'), ('Manufacturing', 'Manufacturing'), ('Cleaning', 'Cleaning'), ('Education', 'Education'), ('Finance', 'Finance'), ('Tourism', 'Tourism'), ('IT', 'IT'), ('Agriculture', 'Agriculture'), ('Others', 'Others')], max_length=50, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='donorfunder',
            name='doner_type',
            field=models.CharField(choices=[('self_', 'self'), ('government', 'government'), ('nGO', 'NGO'), ('grant', 'Grant'), ('International', 'International'), ('Other', 'Other')], max_length=50, verbose_name='Donor Type'),
        ),
        migrations.AlterField(
            model_name='donorfunder',
            name='investment_type',
            field=models.CharField(choices=[('selection', 'selection'), ('finance', 'finance'), ('working_space', 'working space'), ('material', 'material'), ('other', 'other')], max_length=50, verbose_name='Investment Type'),
        ),
        migrations.AlterField(
            model_name='donorfunder',
            name='level',
            field=models.CharField(choices=[('pre', 'Pre-Startup'), ('mid', 'Mid-Startup'), ('early', 'Early Trsction'), ('market', 'In-Market')], max_length=50, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='donorfunder',
            name='maxInvestRange',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Investment Range'),
        ),
        migrations.AlterField(
            model_name='ethregion',
            name='region_name',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Dire Dawa', 'Dire Dawa'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Sidama', 'Sidama '), ('South West Peoples', 'South West'), ('SNNP', 'SNNP'), ('Tigray', 'Tigray')], max_length=50, unique=True, verbose_name='Region Name'),
        ),
        migrations.AlterField(
            model_name='goveroment',
            name='goveroment_type',
            field=models.CharField(choices=[('ministry_offices', 'Ministry offices'), ('universities', 'Universities'), ('other', 'other')], max_length=50, verbose_name='Government type'),
        ),
        migrations.AlterField(
            model_name='goveroment',
            name='level',
            field=models.CharField(choices=[('pre', 'Pre-Startup'), ('mid', 'Mid-Startup'), ('early', 'Early Trsction'), ('market', 'In-Market')], max_length=50, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='focusIndustry',
            field=models.CharField(max_length=30, verbose_name='Focus Industry'),
        ),
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='funded_by',
            field=models.CharField(choices=[('self_', 'self'), ('government', 'government'), ('nGO', 'NGO'), ('grant', 'Grant'), ('International', 'International'), ('Other', 'Other')], max_length=50, verbose_name='Funded By'),
        ),
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='level',
            field=models.CharField(choices=[('pre', 'Pre-Startup'), ('mid', 'Mid-Startup'), ('early', 'Early Trsction'), ('market', 'In-Market')], max_length=50, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='ownership',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Incubation'), ('NGO', 'NGO'), ('Government', 'Government'), ('Other', 'Other')], max_length=50, verbose_name='Owner Ship'),
        ),
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='program_duration',
            field=models.CharField(choices=[('less_than_3_month', 'less than 3 month'), ('3_to_6 months', '3 to 6 months'), ('6_months_to_a_year', '6 months to a year'), ('1_year_to_two_years', '1 year to two years'), ('International', 'International'), ('Other', 'Other')], max_length=50, verbose_name='Program Duration'),
        ),
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='service',
            field=models.CharField(choices=[('Acceleration', 'Acceleration'), ('Incubation', 'Incubation'), ('Hub', 'Hub')], max_length=50, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='airelated_expriance',
            field=models.CharField(max_length=50, verbose_name='AI Related Experience'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='mentor/attachments', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='educationalLevel',
            field=models.CharField(max_length=50, verbose_name='Educational Level'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='educational_background',
            field=models.CharField(max_length=50, verbose_name='Educational Background'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_area',
            field=models.CharField(max_length=50, verbose_name='Mentor Area'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=15, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Sex/Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middile_name',
            field=models.CharField(max_length=15, verbose_name='Middile Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='user_pic/%Y/%m/%d', validators=[main.models.validate_image], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_email',
            field=models.EmailField(max_length=150, verbose_name='Alternate Email'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='market_scope',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=50, verbose_name='Market Scope'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('pre start-up( early-stage)', 'pre start-up( early-stage)'), ('mid start-up', 'mid start-up'), ('in-market', 'in-market')], max_length=50, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='wereda',
            name='wereda_name',
            field=models.CharField(max_length=30, verbose_name='Wereda Name'),
        ),
    ]
