# Generated by Django 4.1.7 on 2023-05-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ethregion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='sector',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Energy', 'Energy'), ('Logistics', 'Logistics'), ('Construction', 'Construction'), ('Education', 'Education'), ('Health', 'Health'), ('Manufacturing', 'Manufacturing'), ('Cleaning', 'Cleaning'), ('Education', 'Education'), ('Finance', 'Finance'), ('Tourism', 'Tourism'), ('IT', 'IT'), ('Agriculture', 'Agriculture'), ('Other', 'Other')], max_length=50, verbose_name='Sector'),
        ),
    ]
