# Generated by Django 4.1.7 on 2023-05-10 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ethregion_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatorsaccelatorshub',
            name='focusIndustry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Focus Industry'), default=list, size=None),
        ),
    ]
