# Generated by Django 4.1.7 on 2023-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_description_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
