# Generated by Django 4.1.7 on 2023-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_connect_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
