# Generated by Django 4.1.7 on 2023-05-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_connect_requester_remove_connect_responser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='from_user',
            new_name='reciver',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='to_user',
            new_name='sender',
        ),
    ]
