# Generated by Django 4.1.7 on 2023-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_connect_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='educationalLevel',
        ),
        migrations.AddField(
            model_name='mentor',
            name='educational_background_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specify Other Background'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='educational_level',
            field=models.CharField(choices=[('no_formal_education', 'No formal education'), ('primary_education', 'Primary education'), ('secondary_education_or_high_school', 'Secondary education or high school'), ('vocational_qualification', 'Vocational qualification'), ('bachelors_degree', 'Bachelors degree'), ('masters_degree', 'Masters degree'), ('doctorate_or_higher', 'Doctorate or higher')], default=1, max_length=50, verbose_name='Educational Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='educational_level_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specify Other Level'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_area_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specify Other Area'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='educational_background',
            field=models.CharField(choices=[('arts_and_humanities', 'Arts and humanities'), ('business_and_management', 'Business and management'), ('computer_science', 'Computer science'), ('education', 'Education'), ('engineering', 'Engineering'), ('health', 'Health'), ('law', 'Law'), ('social_sciences', 'Social sciences'), ('natural_sciences', 'Natural sciences')], max_length=50, verbose_name='Educational Background'),
        ),
    ]
