# Generated by Django 4.1.7 on 2023-05-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_from_user_messages_reciver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='reciver',
            new_name='reciever',
        ),
    ]
