# Generated by Django 4.1.7 on 2023-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_mentor_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_area',
            field=models.CharField(choices=[('legal_advice', 'legal advice'), ('business_model', 'business model'), ('innovation_management', 'innovation management'), ('intellectual_property', 'intellectual property'), ('other', 'Other')], max_length=50, verbose_name='Mentor Area'),
        ),
    ]
